name: deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python env
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt

    - name: Test with pytest
      working-directory: ./src
      run: ENABLE_TEST=True pytest -vv -p no:warnings

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python env
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/prod.txt

    - name: make dist folder
      run: mkdir -p dist

    - name: Build app
      run: python ./script/build.py src/ --requirements requirements/base.txt -o dist/app.pyz --main manage:main --include *.mo *.html *.txt.gz *.json pytz/* *.pyc *.so* *.pyd* -exclude boto3/* botocore/* -q --compress

    - name: Upload app artifact
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: dist/app.pyz
